---
# roles/nginx/tasks/main.yml
- name: Install Nginx web server
  become: true
  apt:
    name: nginx
    state: latest

- name: Nginx service state
  become: true
  service: name=nginx state=started enabled=yes

- name: Delete nginx default files
  become: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
    - /var/www/html/index.nginx-debian.html

- name: Add Symfony config template to the Nginx available sites
  become: true
  template:
    src: templates/symfony.conf
    dest: "/etc/nginx/sites-available/{{ server_name }}"

- name: Enable Symfony config template from Nginx available sites
  become: true
  file:
    src: "/etc/nginx/sites-available/{{ server_name }}"
    dest: "/etc/nginx/sites-enabled/{{ server_name }}"
    state: link
  notify:
    - restart nginx

- name: Add enabled Nginx site to /etc/hosts
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ server_name }}"
    line: "127.0.0.1 {{ server_name }}"
