---
# roles/common/tasks/main.yml

- name: Update APT package manager repositories cache
  become: true
  apt:
    update_cache: yes

- name: Upgrade installed packages
  become: true
  apt:
    upgrade: dist

- name: Install low-level utilities
  become: true
  apt:
    name:
      - zip
      - unzip

- name: Install Git VCS
  become: true
  apt:
    name: git
    state: latest
