---
# roles/application/tasks/main.yml
- name: Create project directory and set its permissions
  become: true
  file:
    path: "{{ symfony_root_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes

- name: Install Symfony 3.4 with flex architecture
  composer:
    command: create-project
    arguments: symfony/website-skeleton {{ symfony_root_dir }} 3.4.*
    no_dev: no
    optimize_autoloader: no
    working_dir: "{{ symfony_root_dir }}"
