---
# roles/application/tasks/main.yml
- name: Add google public key
  become: true
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Ensure Ubuntu sources list file exists
  become: true
  file:
    path: /etc/apt/sources.list.d/google.list
    owner: root
    mode: 0644
    state: touch

- name: Ensure google package is in sources list
  become: true
  lineinfile:
    dest: /etc/apt/sources.list.d/google.list
    regexp: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
    line: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
    state: present

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install utilities for symfony/panther
  become: true
  apt:
    name:
      - libnss3-dev
      - google-chrome-stable

- name: Check if application is already installed
  stat:
    path: "{{ symfony_root_dir }}"
  register: symfony_folder

- debug:
    msg: "Application is already installed, skipping next 2 steps"
  when: symfony_folder.stat.exists

- name: Create project directory and set its permissions
  become: true
  file:
    path: "{{ symfony_root_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
  when: not symfony_folder.stat.exists

- name: Install latest version of symfony/website-skeleton
  composer:
    command: create-project
    arguments: symfony/website-skeleton {{ symfony_root_dir }}
    no_dev: no
    optimize_autoloader: no
    working_dir: "{{ symfony_root_dir }}"
  when: not symfony_folder.stat.exists
