---
# roles/application/tasks/main.yml
- name: Create project directory and set its permissions
  become: true
  file:
    path: "{{ symfony_root_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes

- name: Checkout Git repository
  git:
    repo: https://github.com/symfony/symfony-standard.git
    dest: "{{ symfony_root_dir }}"
    force: yes

- name: Install Composer's dependencies
  composer:
    working_dir: "{{ symfony_root_dir }}"
    no_dev: no
