---
# roles/php/tasks/main.yml
- name: Install PHP packages
  become: true
  apt:
    name:
      - php-cli
      - php-curl
      - php-fpm
      - php-xml
      - php-mysql
    state: latest

- name: Set date.timezone for CLI
  become: true
  lineinfile:
    dest: /etc/php/7.2/cli/php.ini
    regexp: "date.timezone ="
    line: "date.timezone = Europe/Paris"

- name: Set date.timezone for FPM
  become: true
  lineinfile:
    dest: /etc/php/7.2/fpm/php.ini
    regexp: "date.timezone ="
    line: "date.timezone = Europe/Paris"
  notify:
    - restart php-fpm

- name: Download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer

- name: Install composer
  become: true
  command: "{{ item }}"
  with_items:
    - "php /tmp/installer"
    - mv composer.phar /usr/local/bin/composer

- name: Remove composer installer
  file:
    path: "/tmp/installer"
    state: absent

- name: Set permissions on Composer
  become: true
  file:
    path: /usr/local/bin/composer
    mode: "a+x"
