---
# roles/php/tasks/main.yml

# Comment this task on Debian 10 or make it conditional
- name: Add ppa:ondrej/php repository
  become: true
  apt_repository:
    repo: ppa:ondrej/php

- name: Install PHP packages
  become: true
  apt:
    name:
      - php7.4-cli
      - php7.4-curl
      - php7.4-fpm
      - php7.4-xml
      - php7.4-mysql
#      - php7.4-pgsql
      - php7.4-mbstring
      - php7.4-zip
    state: latest

- name: Set date.timezone for CLI
  become: true
  lineinfile:
    dest: /etc/php/7.4/cli/php.ini
    regexp: "date.timezone ="
    line: "date.timezone = Europe/Paris"

- name: Set date.timezone for FPM
  become: true
  lineinfile:
    dest: /etc/php/7.4/fpm/php.ini
    regexp: "date.timezone ="
    line: "date.timezone = Europe/Paris"
  notify:
    - restart php-fpm

- name: Download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer

- name: Install composer
  become: true
  command: "{{ item }}"
  with_items:
    - "php /tmp/installer"
    - mv composer.phar /usr/local/bin/composer

- name: Remove composer installer
  file:
    path: "/tmp/installer"
    state: absent

- name: Set permissions on Composer
  become: true
  file:
    path: /usr/local/bin/composer
    mode: "a+x"
